# Generated by Django 5.0.6 on 2024-06-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
